language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
env:
- PACKAGE=packages/eslint-config-eventbrite
- PACKAGE=packages/eslint-config-eventbrite-react
- PACKAGE=packages/eslint-config-eventbrite-legacy
script: cd $PACKAGE && npm install && npm test
#deploy:
#  provider: npm
#  email: npmjs+eng@eventbrite.com
#  api_key:
#    secure: WhYIjJQQBvZktOxQL2vbkP7WJ+l1o5lsRYcEXYvAjXXgJAgk6D8OCzUKt1ef8zbgAHimI4CIqw5aQO5Ok6aUDNhJOHZaFOQ5FC1hzj6mdOB8Dv9Bulx/nPdJOTlpOGJ0dCyfnlXlPUfMFdcOGdNc6v469uvG/V+zmZo0ZpH14XwFvLb76XVVsBKLRwz47dAPXYF9mfp0l2biaw33hJXrLvnQBtuADpzk7vvVHVSSu/mDuCxW2f3eQS5kPFOOysmJOLeISAhUN3RGG/XEruxaEfUGASosZxIMU7DWAmgbf1ItlA2ifPOUYcs9nGBfufz7mIXE4OnBlI3YPa+baapqfOlPjgRqI2DGWfnRiLXzRNY4F7Q49e/WB/IJvX4qVL04wHYSa4SYKkLKGYEP+CBNgsVrZZK+Eb8NhCn7RUBdhcvn8vXyB/136gTXJapetD5Dol8S5NuFBLd7nXxga9arqZb3sVdjLOlrz24QRfBROgaCHsx+rtKRuVO32NbWYz4WF8s0cO2W+RLsKQu2HRq767HCAIEC7ua2BZAKqO5pEypgdZOR0AbHp3IA99mkjNMSFfu6u0SN+Dc3T8wggFlkWL8S2UOOhNjTzotAoKAPyIEhlVpln378IjtPJWjMuE4WJ3AoFC46rcb+4sLXhNxQS38T4e8PNki6qXY5vnrjBJ4=
#  on:
#    tags: true
#    repo: eventbrite/javascript
